language: python
python:
  - 2.7
script: make coverage
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
install:
  - pip install -q Django==$DJANGO -r example/requirements-travis.txt
branches:
  only:
    - master
after_success:
  - coveralls
