language: python

python:
  - 2.6
  - 2.7

before_install:
  - sudo apt-get install -y libxml2-dev libxslt-dev

script:  make test

env:
  - DJANGO=1.4.5
  - DJANGO=1.5.1

install:
  - pip install -q Django==$DJANGO -r example/requirements.txt --use-mirrors
