language: python
python:
  - 2.6
  - 2.7
script: make coverage
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
install:
  - pip install -q Django==$DJANGO -r example/requirements-travis.txt
branches:
  only:
    - master
after_success:
  - coveralls
